# Generated by Django 4.2.28 on 2026-03-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('release_date', models.DateField()),
                ('poster', models.ImageField(upload_to='./movies')),
                ('genre', models.ManyToManyField(to='core.genre')),
                ('language', models.ManyToManyField(to='core.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
