# Generated by Django 4.2.28 on 2026-03-03 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("slot", "0001_initial"),
        ("theater", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="theater",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="theater.theater",
            ),
        ),
    ]
