# Generated by Django 4.2.28 on 2026-03-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("movie", "0001_initial"),
        ("theater", "0001_initial"),
        ("slot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slotseat",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slot_seats",
                to="theater.seat",
            ),
        ),
        migrations.AddField(
            model_name="slotseat",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slot_seats",
                to="slot.slot",
            ),
        ),
        migrations.AddField(
            model_name="slot",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="core.language",
            ),
        ),
        migrations.AddField(
            model_name="slot",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="slots", to="movie.movie"
            ),
        ),
        migrations.AddField(
            model_name="slot",
            name="theater",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="theater.theater",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="slotseat",
            unique_together={("slot", "seat")},
        ),
    ]
